data_path: "data"
chroma_path: "chroma"

loaders:
  pdf: true
  docx: true
  json: true
  pptx: false
  html: false
  csv: false
  doc: true
  rtf: false
  md: true
  txt: true
  excel: false
  images_ocr: false
  video: false
  
chunking:
  text:
    chunk_size: 800
    overlap: 80
